name: hw_dashboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  bloc: ^8.1.4
  excel: ^4.0.3
  file_saver: ^0.2.12
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_form_builder: ^9.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  path_provider: ^2.1.3
  table_sticky_headers: ^2.0.5

  tools:
    path: tools
  client_tools:
    path: client_tools

dev_dependencies:
  flutter_test:
    sdk: flutter
  # build_runner: ^2.4.9
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packagesÂ·

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # 

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Bold.ttf
          weight: 700
        - asset: fonts/NotoSansSC-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSansSC-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansSC-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansSC-Light.ttf
          weight: 300
  # fonts:
  #   - family: NotoSansSC
  #     fonts:
  #       - asset: client_tools/assets/fonts/NotoSansSC-Bold.ttf
  #         weight: 700
  #       - asset: client_tools/assets/fonts/NotoSansSC-SemiBold.ttf
  #         weight: 600
  #       - asset: client_tools/assets/fonts/NotoSansSC-Medium.ttf
  #         weight: 500
  #       - asset: client_tools/assets/fonts/NotoSansSC-Regular.ttf
  #         weight: 400
  #       - asset: client_tools/assets/fonts/NotoSansSC-Light.ttf
  #         weight: 300
