name: api
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0-190.1.beta

dependencies:
  crypt: ^4.3.1
  dart_frog: ^1.1.0
  envied: ^0.5.4+1
  mongo_dart: ^0.10.1
  dart_jsonwebtoken: ^2.13.0
  
  tools:
    path: ../tools

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9
